# Generated by Django 2.1.5 on 2019-01-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppmt', '0003_auto_20190131_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(default='SOME STRING', max_length=500)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(default='SOME STRING', max_length=500)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
