# Generated by Django 2.1.7 on 2019-06-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_logo',
            new_name='album_log',
        ),
    ]
