# Generated by Django 2.1.5 on 2019-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='category',
            field=models.CharField(default='SOME STRING', max_length=15),
        ),
    ]
