# Generated by Django 2.1.3 on 2018-12-04 03:56

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
        migrations.AlterModelTable(
            name='song',
            table='song',
        ),
    ]
