# Generated by Django 2.1.4 on 2018-12-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_favorite',
        ),
    ]
